version: '3.8'
services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_b_db
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./dbseed.sql:/docker-entrypoint-initdb.d/init.sql

  app_server:
    platform: linux/amd64

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=task_b_db
      - DATABASE_URL=postgres
      - APP_PORT=8000

volumes:
  db:
    driver: local
