version: '3.8'
services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testenvpassword
    ports:
      - '54322:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local